modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Mrbysco/SpellChecker/issues"
license="LGPL-3.0"

[[mods]]
modId="spellchecker"
version="${file.jarVersion}"
displayName="Spell Checker"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spell-checker"
authors="Mrbysco"
description='''
Need your spelling checked?
'''
logoFile="logo.png"

[[dependencies.spellchecker]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"