# Project
version=9.0.0
group=com.mrbysco.spellchecker

# Common
minecraft_version=1.21.5

# NeoForge
neo_version=21.5.26-beta
neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.119.6+1.21.5
fabric_loader_version=0.16.11
cloth_config_version=18.0.145
mod_menu_version=14.0.0-rc.2

# Mod options
mod_name=SpellChecker
mod_author=Mrbysco
mod_id=spellchecker

#Publishing
curseforge_id=306068
modrinth_id=xrdXfWii

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false