modLoader="javafml"
loaderVersion="[34,)"
license="All Rights Reserved"

[[mods]]
modId="spellchecker"
version="${file.jarVersion}"
displayName="Spell Checker"
displayURL="https://minecraft.curseforge.com/projects/spell-checker"
authors="Mrbysco"
description='''Need your spelling checked?'''
credits="SpeedRider17104 for the suggestion"
logoFile="logo.png"